### ISSUE TITLE
when will we have the code

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/BuildCast#1]
its more than a month now but still no code is in this repo at all, Please can I know when can we expect the code here?

**Comment by msammels** [comment]
I am also interested to know this. I've been looking for code examples of the fluent design system for a while now.

**Comment by hupo376787** [comment]
Still no code now...

**Comment by StuRamsey** [comment]
And still no code. Maybe when they said '**_Source code will be published here shortly_**', they were measuring the time span in Microsoft minutes, we all know how long they cam be!

**Comment by renatorabelo** [comment]
"and still no code".  Frankly,  Microsoft does not give a shit nowadays.

**Comment by touseefbsb** [comment]
its odd if they cant maintain a repo they shouldnt create it in the first place.

**Comment by clarkezone** [comment]
Sorry about this folks, it's coming tomorrow.
