### ISSUE TITLE
No code yet??

### ISSUE THREAD

**Issue by michaelcoelsch** [Microsoft/BuildCast#2]

**Comment by Meai1** [comment]
IT'S A FREAKING JOKE

"OH YEAH WE ONLY DIDNT RELEASE CODE BECAUSE WE WANTED IT TO BE SUPER POLISHED BUT WE TOOOOTALLY REALIZE HOW LAME NO CODE RELEASE IS WITH A PRESENTATION"

HA
HA
HA

**Comment by clarkezone** [comment]
Sorry about this.  It's coming tomorrow.
